// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcDxIKCVUb0YiE6HNvo9sBF0OLGaL14Xs',
    appId: '1:304492835662:web:3b083e0d2584f4e271e41f',
    messagingSenderId: '304492835662',
    projectId: 'quiz-app-inno',
    authDomain: 'quiz-app-inno.firebaseapp.com',
    storageBucket: 'quiz-app-inno.appspot.com',
    measurementId: 'G-2C2FZK3N8P',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0K6aSkut04_vuR1xJMkaYFYLnwmWdC7U',
    appId: '1:304492835662:ios:daffec8fba2726ce71e41f',
    messagingSenderId: '304492835662',
    projectId: 'quiz-app-inno',
    storageBucket: 'quiz-app-inno.appspot.com',
    iosClientId: '304492835662-93gna6klpqqviv886qjcu5q1oklsvdsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.innoQuizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0K6aSkut04_vuR1xJMkaYFYLnwmWdC7U',
    appId: '1:304492835662:ios:daffec8fba2726ce71e41f',
    messagingSenderId: '304492835662',
    projectId: 'quiz-app-inno',
    storageBucket: 'quiz-app-inno.appspot.com',
    iosClientId: '304492835662-93gna6klpqqviv886qjcu5q1oklsvdsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.innoQuizApp',
  );
}
