name: Flutter CI

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Setup environment in order to build the Android app.
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2

    # Get flutter dependencies.
    - run: flutter pub get

    # Statically analyze the Dart code for any errors.
    - run: flutter analyze .

    # Build web.
    - run: flutter build web --base-href /inno_quiz_app/

    - name: Deploy Web
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./build/web
        github_token: ${{ secrets.GITHUB_TOKEN }}